#!/bin/sh

BACKUP_FOLDER=/backup/monthly
NOW=$(date +"%FT%H%M%z")

echo $NOW

MHOST=$MYSQL_CONTAINER_NAME
MPASS=$MYSQL_ROOT_PASSWORD
MUSER=root

[ ! -d "$BACKUP_FOLDER" ] && mkdir --parents $BACKUP_FOLDER

FILE_SQL=${BACKUP_FOLDER}/mariadb-${NOW}.sql.gz
FILE_IMAGES=${BACKUP_FOLDER}/wiki_images-${NOW}.gz

mysqldump -h $MHOST -u $MUSER -p${MPASS} --all-databases | gzip -9 > $FILE_SQL
tar -zcvf $FILE_IMAGES --exclude /var/www/images/thumb/ /var/www/

# keep ~3 months
find $BACKUP_FOLDER -maxdepth 1 -mtime +100 -type f -delete