#!/bin/sh

BACKUP_FOLDER=/backup/daily
NOW=$(date +"%FT%H%M%z")

echo "${NOW}"

MIN_WAIT=0
MAX_WAIT=30
SLEEP_TIME=$((MIN_WAIT + RANDOM % (MAX_WAIT - MIN_WAIT)))
echo "sleep ${SLEEP_TIME} seconds"
sleep "${SLEEP_TIME}"
echo "slept ${SLEEP_TIME} seconds"

MHOST=${MYSQL_CONTAINER_NAME}
MPASS=${MYSQL_ROOT_PASSWORD}
MUSER=root

echo "connecting to ${MHOST} as ${MUSER}"

[ ! -d "${BACKUP_FOLDER}" ] && mkdir --parents "${BACKUP_FOLDER}"

FILE_SQL="${BACKUP_FOLDER}/mariadb-${NOW}.sql.gz"
FILE_IMAGES="${BACKUP_FOLDER}/wiki_images-${NOW}.gz"

mariadb-dump -h "${MHOST}" -u "${MUSER}" -p"${MPASS}" --all-databases | gzip -9 > "${FILE_SQL}"
tar -zcvf "${FILE_IMAGES}" --exclude /var/www/images/thumb/ /var/www/

# keep 3 days
find $BACKUP_FOLDER -maxdepth 1 -mtime +3 -type f -delete